apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/version: latest
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: afk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: "/afk-no"
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1instance
        value: fint-kontroll-sso_afk-no
    target:
      kind: FLAISSso
      name: fint-kontroll-sso
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: "/afk-no"
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1instance
        value: fint-kontroll-layout_afk-no
      - op: add
        path: "/spec/env/-"
        value:
          name: LAYOUT_CONFIGURATION_URI
          value: http://fint-kontroll-layout-config-service:8080/afk-no/api/layout/configuration
    target:
      kind: Application
      name: fint-kontroll-layout
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: /afk-no/api/layout
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1instance
        value: fint-kontroll-layout-config-service_afk-no
    target:
      kind: Application
      name: fint-kontroll-layout-config-service

