apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-layout
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: fint-kontroll-layout
    app.kubernetes.io/instance: fint-kontroll-layout_fintlabs-no
spec:
  port: 3000
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-layout:sha-f599119
  prometheus:
    enabled: true
    port: "3000"
    path: /metrics
  url:
    hostname: kontroll.vigoiks.no
    basePath: /alpha/fintlabs-no
  ingress:
    enabled: true
  env:
    - name: LAYOUT_CONFIGURATION_URI
      value: http://fint-kontroll-layout-config-service:8080/alpha/fintlabs-no/api/layout/configuration