apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-layout
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/flais-layout-config-service:latest
  imagePullPolicy: always
  url:
    hostname: kontroll.vigoiks.no
    basePath: /alpha/fintlabs-no/api/layout
  ingress:
    enabled: true
  database:
    enabled: true