name: CD Forwad Auth

on: [ push ]

jobs:
  deploy-to-aks:
    name: deploy for ${{ matrix.org }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        org:
          - fintlabs-no
          - viken-no
        cluster:
          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
        #          - aks-api-fint-2022-02-08
        #          - aks-pwf-fint-2021-10-20
        exclude:
          - org: viken-no
            cluster: aks-alpha-fint-2021-11-18
          - org: fintlabs-no
            cluster: aks-beta-fint-2021-11-23

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Get environment
        uses: actions/github-script@v6
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1]
          result-encoding: string

      - name: Get resource group name
        uses: actions/github-script@v6
        id: resource-group
        with:
          script: return 'rg-aks-${{ steps.environment.outputs.result }}'
          result-encoding: string

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v2.4
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/auth-forward/overlays/${{ steps.environment.outputs.result }}/${{ matrix.org }}'

      - name: Set the target cluster
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"
          cluster-name: '${{ matrix.cluster }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'

      - name: Deploy
        uses: azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build-and-push.outputs.tags }}
          namespace: ${{ matrix.org }}